// attract OCS palette — generated by tools/png2raw.py
// 16 entries, 12-bit 0x0RGB each.
static const uint16_t kAttractPalette[16] = {
    0x000,  // #040404
    0x333,  // #333333
    0x444,  // #4f4f4f
    0x832,  // #833c2d
    0xd98,  // #de988a
    0x56b,  // #5462bc
    0x012,  // #001624
    0x580,  // #52840d
    0x460,  // #4f6200
    0x982,  // #9f8f2f
    0x000,  // (unused)
    0x000,  // (unused)
    0x000,  // (unused)
    0x000,  // (unused)
    0x000,  // (unused)
    0x000,  // (unused)
};
