// cockpit OCS palette — generated by tools/png2raw.py
// 4 entries, 12-bit 0x0RGB each.
static const uint16_t kCockpitPalette[4] = {
    0x000,  // #000000
    0x444,  // #444444
    0x333,  // #333333
    0x832,  // #883322
};
