// terrain OCS palette — generated by tools/png2raw.py
// 4 entries, 12-bit 0x0RGB each.
static const uint16_t kTerrainPalette[4] = {
    0x000,  // #040404
    0x444,  // #4f4f4f
    0x580,  // #52840d
    0x000,  // (unused)
};
