// title OCS palette — generated by tools/png2raw.py
// 4 entries, 12-bit 0x0RGB each.
static const uint16_t kTitlePalette[4] = {
    0x444,  // #444444
    0x56c,  // #5566cc
    0x333,  // #333333
    0x000,  // #000000
};
