// M2 attract scene: double-buffered copper lists rebuilt per frame.
//
// The attract screen bitmap is static (320x200 4-bitplane from atari000.png).
// M2 adds:
//  - per-frame copper rebuilds via a double-buffered pair (infrastructure for M3+)
//  - palette fade-in over the first 64 VBIs, then a slow hue sweep
//  - WAIT instructions at region boundaries (title/terrain y=44 / cockpit y=128)
//    ready to carry different per-region colours in M3+
//
// Copper list layout per frame:
//   [0]      copperWait(16,0)          — initial wait (set by CopperList ctor)
//   [1..12]  setPlayfield              — mode, DIWSTRT/STOP, DDFSTRT/STOP, modulo
//   [13..20] showBitmap                — 4 × (bplXpth, bplXptl)
//   [21..36] setPalette                — 16 × COLOR register moves
//   [37]     copperWait(kTerrainLine)  — terrain split point (future use)
//   [38]     copperWait(kCockpitLine)  — cockpit split point (future use)
//   [63]     copperWait(255,254)       — end (set by CopperList ctor)

#define ECS_SPECIFIC
#include <hardware/dmabits.h>
#include "../framework/AmigaHardware.h"
#include "../framework/CopperList.h"
#include "../framework/Bitmap.h"
#include "../framework/Palette.h"
#include "AttractScene.h"

// Generated by tools/png2raw.py from atari000.png
#include "../assets/attract_pal.h"

// incbin.s: attract.raw is in .MEMF_CHIP
extern "C" uint8_t attract_raw[];

// Bitmap geometry
static const uint16_t kW  = 320;
static const uint16_t kH  = 200;
static const uint8_t  kBP = 4;

// Copper list size: setPlayfield(12) + showBitmap(8) + setPalette(16) + 2 WAITs + 2(start/end) = 40.
// Pad to 64 for future per-region colour writes.
static const uint32_t kCopperLen = 64;

// PAL beam coordinates of region boundaries.
// Display starts at beam line (centerY - height/2) = 168 - 100 = 68.
// Terrain starts at bitmap row 44  → beam 68 + 44  = 112.
// Cockpit starts at bitmap row 128 → beam 68 + 128 = 196.
static const uint8_t kTerrainLine = 112;
static const uint8_t kCockpitLine = 196;

// ---- animation ---------------------------------------------------------------
// Fade-in: 0..64 → fade level 0..16 (Palette::setFade range).
// After full brightness: a slow hue sweep on the sky/background (colour index 5).
// Sweep table: 8 blue hues repeated, one step per 4 frames.
static const uint16_t kSkyHues[8] = {
    0x46b, 0x56b, 0x56c, 0x46c, 0x36b, 0x46a, 0x56b, 0x56a
};

static void animatePalette(Palette* palette, uint16_t frame)
{
    if (frame < 64) {
        // Fade in: map frame [0..63] → fade [0..16]
        palette->setFade((frame * 17) >> 6);
    } else {
        if (palette->fade() < 16) palette->setFade(16);
        // Slow hue sweep on the sky-blue entry (idx 5 = 0x56b initially)
        uint16_t step = (uint16_t)((frame - 64) >> 2) & 7;
        uint16_t newSky = kSkyHues[step];
        // Directly patch source palette entry 5 and re-apply fade
        // (Palette has no setColor, so we rebuild from the array).
        // For now: mutate kAttractPalette copy via a local override array.
        // (Simple approach: rebuild palette from scratch each time — cheap at 16 entries.)
        uint16_t pal[16];
        for (int i = 0; i < 16; i++) pal[i] = kAttractPalette[i];
        pal[5] = newSky;
        palette->setPalette(pal, 16);
        palette->setFade(16);
    }
}

// ---- copper list builder -----------------------------------------------------
void AttractScene::buildCopperList(CopperList* cl, uint16_t frame)
{
    animatePalette(palette, frame);

    uint32_t idx = 1;  // slot 0 = initial copperWait set by ctor
    idx = cl->setPlayfield(idx, kW, kH, kBP, /*interleaved*/true);
    cl->showBitmap(idx, *bitmap);
    idx += 2 * kBP;                           // showBitmap: 2 words × 4 planes
    idx = cl->setPalette(idx, *palette);      // 16 colour moves

    // Region boundary WAITs — no colour changes yet, placeholder for M3+.
    // These occupy slots in the list so M3 can insert colour writes here.
    cl->data()[idx++] = copperWait(kTerrainLine, 0);
    cl->data()[idx++] = copperWait(kCockpitLine, 0);
    // Remaining slots up to [63] are the end copperWait from ctor.
}

// ---- public interface --------------------------------------------------------
void AttractScene::initialize()
{
    Palette::initialize();
    palette = new Palette(kAttractPalette, 16, /*fade*/0);  // start dark
    bitmap  = new Bitmap(attract_raw, kW, kH, kBP, /*interleaved*/true);

    for (int i = 0; i < 2; i++) {
        copperLists[i] = CopperList::allocate(kCopperLen);
    }

    if (!palette || !bitmap || !copperLists[0] || !copperLists[1]) return;

    // Build both copper lists (frame=0) and activate #0.
    buildCopperList(copperLists[0], 0);
    buildCopperList(copperLists[1], 0);
    active = 0;
    AmigaHardware::setCopperList(*copperLists[active], true);
}

void AttractScene::update(uint16_t frame)
{
    // Build the OFF-SCREEN list and queue it for the next frame.
    uint8_t next = 1 - active;
    buildCopperList(copperLists[next], frame);
    AmigaHardware::setCopperList(*copperLists[next], false);
    active = next;
}

void AttractScene::render()
{
    // All rendering is copper-driven; no CPU work per frame.
}

void AttractScene::shutdown()
{
    for (int i = 0; i < 2; i++) {
        delete copperLists[i];
        copperLists[i] = nullptr;
    }
    delete bitmap;  bitmap  = nullptr;
    delete palette; palette = nullptr;
}
