// M1 attract scene: static 320×200 4-bitplane bitmap with flat OCS palette.
// attract.raw is linked into chip RAM via incbin.s; Palette/Bitmap/CopperList
// are the dA JoRMaS framework classes (no assembler).

#define ECS_SPECIFIC
#include <hardware/dmabits.h>
#include "../framework/AmigaHardware.h"
#include "../framework/CopperList.h"
#include "../framework/Bitmap.h"
#include "../framework/Palette.h"
#include "AttractScene.h"

// Generated by tools/png2raw.py from atari000.png (source: 336×240 NTSC frame)
#include "../assets/attract_pal.h"

// incbin.s declares this symbol in .MEMF_CHIP so bitplane DMA can reach it.
extern "C" uint8_t attract_raw[];

// Copper list size: setPlayfield(12) + showBitmap(8) + setPalette(16) + 2 (start/end) = 38.
// Allocate 64 to leave room for later additions (M2 colour splits).
static const uint32_t kCopperListLen = 64;

// Bitmap dimensions
static const uint16_t kW = 320;
static const uint16_t kH = 200;
static const uint8_t  kBP = 4;

void AttractScene::initialize()
{
    Palette::initialize();
    palette    = new Palette(kAttractPalette, 16);
    bitmap     = new Bitmap(attract_raw, kW, kH, kBP, /*interleaved*/true);
    copperList = CopperList::allocate(kCopperListLen);

    if (!palette || !bitmap || !copperList) return;

    // Build the copper list:
    //   [0]       copperWait(16,0)           — initial wait (set by CopperList ctor)
    //   [1..12]   setPlayfield               — mode, DIWSTRT/STOP, DDFSTRT/STOP, modulo
    //   [13..20]  showBitmap                 — 4 × (bplXpth, bplXptl)
    //   [21..36]  setPalette                 — 16 × color register moves
    //   [63]      copperWait(255,254)         — end (set by CopperList ctor)
    uint32_t idx = 1;  // slot 0 is the initial wait
    idx = copperList->setPlayfield(idx, kW, kH, kBP, /*interleaved*/true);
    copperList->showBitmap(idx, *bitmap);
    idx += 2 * kBP;  // showBitmap emitted 2 words × 4 planes = 8 entries
    copperList->setPalette(idx, *palette);

    AmigaHardware::setCopperList(*copperList, true);
}

void AttractScene::update(uint16_t /*frame*/)
{
    // M1: static frame, nothing to update.
}

void AttractScene::render()
{
    // M1: copper list is static, no per-frame CPU work.
}

void AttractScene::shutdown()
{
    delete copperList; copperList = nullptr;
    delete bitmap;     bitmap     = nullptr;
    delete palette;    palette    = nullptr;
}
