; Generated by tools/rof_data_layout.py; do not edit.
data_ROM0_OFFSET = $0000
data_ROM0_SIZE = $75d1
data_PACK0_OFFSET = $0000
data_ROM1_OFFSET = $8000
data_ROM1_SIZE = $113b
data_PACK1_OFFSET = $75d1
data_ROM2_OFFSET = $e000
data_ROM2_SIZE = $1fda
data_PACK2_OFFSET = $870c
data_SIZE = $0000a6e6
data_CRC32 = $da1ddf54
