#pragma once
#include "framework/CopperList.h"

class Bitmap;
class Sprite;

// The two scenes' 16-luminance ramps, generated by tools/gen_gtia9_pal.py (see that script for
// why amiga/assets/atari_pal.h cannot serve GTIA mode 9: it ignores bit 0 of the colour byte,
// collapsing sixteen luminances to eight).  Defined in Gtia9CopperList.cpp.
extern const uint16_t kGtia9Pal0[16];   // COLBK hue $00 — the station, greyscale
extern const uint16_t kGtia9Pal1[16];   // COLBK hue $10 — the logo, gold

// Gtia9CopperList — the copper list for BOTH boot scenes: the Lucasfilm Games logo (scene 1)
// and the space-station cinematic (scene 2).
//
// They are the same screen mode.  Each is ANTIC mode F under GTIA mode 9 (PRIOR bits 7:6 = 01):
// 80 fat pixels per scanline, each a 4-bit LUMINANCE of the single COLBK hue.  On the Amiga
// that is 4 bitplanes, 320 px wide (one GTIA pixel = 4 lores px), with a 16-entry palette of
// one hue's luminance ramp.  Only three things differ between the two scenes, so they are
// buildLayout() parameters rather than two classes:
//
//              leading blank lines   mode-F rows   COLBK hue        moves per frame
//   Logo         8 x $70 = 64            62        $10 gold    the sparkle sprite + its colour
//   Station      1 x $70 =  8           192        $00 grey    the window row + the PMG sprites
//
// The two also share ONE tall field bitmap (RescueOnFractalus::bootFieldBitmap) and one
// decoder, because the station needs 340 rows of it and the logo only 62.
//
// SCROLL (station only).  The Atari display list at $B800 is 340 mode-F entries and its own JMP
// operand walks DOWN it 3 bytes per step, with a JVB moved along $0240 bytes behind, so the
// visible window is always exactly 192 rows and the picture slides down.  We decode all 340 rows
// once and scroll by moving the four bitplane POINTERS, which makes the scroll free.
// ⚠ setWindowRow() must be called from the VBI ISR only: a torn bitplane pointer garbages the
// whole frame (see the amiga-copper-lessons memory).
//
// THREE REGIONS, because neither display list fills our 216-line display window: the leading
// blank lines, the mode-F rows, then nothing (COLBK) for whatever is left.  The blank regions
// cannot come from bitmap padding — the station's window slides, so a fixed pad would scroll
// into view — so they point all four planes at one cleared line with modulo -40, which re-reads
// it every scanline: pen 0 = color00 = the hue's luminance 0.
class Gtia9CopperList : public CopperList {
public:
    Gtia9CopperList();
    ~Gtia9CopperList();

    // One-time layout.  `topLines` leading blank scanlines, then `rows` mode-F rows of `field`
    // starting at field row 0; `pal16` is the scene's 16-entry luminance ramp (tools/
    // gen_gtia9_pal.py).  All 8 sprites start null and every sprite colour black.
    void buildLayout(const Bitmap& field, uint16_t topLines, uint16_t rows,
                     const uint16_t* pal16, const Sprite& nullSprite);

    // Per-frame (VBI ISR ONLY): show the window starting at field row `row` — the scroll.
    void setWindowRow(uint16_t row);

    // Per-frame: one colour of one sprite PAIR (pair 0..3 -> COLOR17/21/25/29 + (which-1)*2).
    // Atari players map to Amiga sprite channels, and OCS gives one palette entry per pair per
    // colour, so each Atari element that shares a colour is put on its own pair.  `which` is 1
    // for a sprite that only fills plane A (every mirror here but one); the station's spacecraft
    // fills BOTH planes of one sprite, so its pen is DATB<<1 | DATA and it uses 2 and 3 as well —
    // that is how GTIA's multi-colour-player OR of COLPM0/COLPM1 is reproduced.
    void setPairColor(uint16_t pair, uint16_t c, uint16_t which = 1);

    // Re-point one sprite channel (VBI ISR only, same reason as setWindowRow).
    void setSpriteOperand(uint16_t channel, const uint16_t* data);

private:
    const Bitmap* field_ = nullptr;   // the tall 4bp field, for setWindowRow's arithmetic
    uint16_t*     blank_ = nullptr;   // one cleared scanline, re-read by the blank regions
};
