#define ECS_SPECIFIC
#include <hardware/custom.h>
#include <graphics/display.h>          // USE_BPLCON3 (ECSENA — keeps BPLCON3 BRDNBLNK live)
#include <proto/exec.h>
#include <exec/memory.h>
#include "Gtia9CopperList.h"
#include "framework/AmigaHardware.h"
#include "framework/Bitmap.h"
#include "framework/Sprite.h"

// ---- display geometry (MUST match RescueOnFractalus.cpp) ---------------------
static const uint16_t kW          = 320;
static const uint16_t kH          = 216;
static const uint8_t  kBP4        = 4;                       // 16 GTIA-9 luminances
static const uint16_t kDisplayTop = 0x2c;
static const uint16_t kCenterY    = kDisplayTop + kH / 2;    // = 0x98

static const int kLineBytes = 40;                            // 320 px lores, one plane
static const int kRowBytes  = kLineBytes * kBP4;             // interleaved row stride = 160
// 4bp interleaved: after fetching its 40 bytes each plane pointer must skip the other three.
static const int16_t kModInterleaved = (int16_t)(kBP4 * kLineBytes - kLineBytes);   // 120

// The two scenes' 16-luminance ramps, generated by tools/gen_gtia9_pal.py; even n reproduces
// atariToOCS(hue | n) exactly and odd n interpolates on the same YIQ curve.  See that script for
// why atariToOCS() alone cannot serve GTIA mode 9.
const uint16_t kGtia9Pal0[16] = {   // COLBK hue $00 — the station, greyscale
    0x000, 0x111, 0x222, 0x222, 0x333, 0x444, 0x555, 0x666,
    0x666, 0x777, 0x888, 0xAAA, 0xBBB, 0xCCC, 0xDDD, 0xEEE,
};
const uint16_t kGtia9Pal1[16] = {   // COLBK hue $10 — the logo, gold
    0x200, 0x310, 0x410, 0x420, 0x530, 0x640, 0x740, 0x851,
    0x962, 0xA73, 0xB84, 0xC95, 0xDA6, 0xEC7, 0xFD9, 0xFEA,
};

// ---- fixed list layout (indices into data_, 32-bit MOVE/WAIT words) ----------
// d[0] = copperWait(16,0) (CopperList ctor).  setPlayfield emits 3 words (BPLCON0 +
// BPL1MOD/BPL2MOD); the constant playfield registers are set once by
// AmigaHardware::setPlayfield in RescueOnFractalus::initialize.
#define INDEX_PLAYFIELD   1
#define INDEX_BPLCON2     (INDEX_PLAYFIELD + 3)    // 4: sprite-vs-playfield priority (1)
#define INDEX_PAL         (INDEX_BPLCON2 + 1)      // 5: color00..color15 (16)
#define INDEX_SPRCOL      (INDEX_PAL + 16)         // 21: the 4 sprite pairs' colours 1..3 (12)
#define INDEX_SPRITES     (INDEX_SPRCOL + 12)      // 33: 8 sprite ptrs (16)
#define INDEX_TOP_MOD     (INDEX_SPRITES + 16)     // 49: bpl1mod/bpl2mod = -40 (2)
#define INDEX_TOP_BPL     (INDEX_TOP_MOD + 2)      // 51: 4 plane ptrs -> the blank line (8)
#define INDEX_WIN_WAIT    (INDEX_TOP_BPL + 8)      // 59: WAIT(first mode-F line - 1, 0xE0) (1)
#define INDEX_WIN_MOD     (INDEX_WIN_WAIT + 1)     // 60: bpl1mod/bpl2mod = 120 (2)
#define INDEX_WIN_BPL     (INDEX_WIN_MOD + 2)      // 62: 4 plane ptrs -> the window (8)
#define INDEX_BOT_WAIT    (INDEX_WIN_BPL + 8)      // 70: WAIT(line past the last row, 0xE0) (1)
#define INDEX_BOT_MOD     (INDEX_BOT_WAIT + 1)     // 71: bpl1mod/bpl2mod = -40 (2)
#define INDEX_BOT_BPL     (INDEX_BOT_MOD + 2)      // 73: 4 plane ptrs -> the blank line (8)
#define INDEX_TERMINATOR  (INDEX_BOT_BPL + 8)      // 81: copperWait(255,254)
#define LIST_LENGTH       (INDEX_TERMINATOR + 1)

Gtia9CopperList::Gtia9CopperList()
    : CopperList((uint32_t*)AllocMem(LIST_LENGTH << 2, MEMF_CHIP | MEMF_CLEAR), LIST_LENGTH, true)
{
    // One cleared scanline the blank regions re-read (modulo -40) so they show pen 0.
    // A little past kLineBytes for Agnus's read-ahead, as EmptyCopperList's filler does.
    blank_ = (uint16_t*)AllocMem(64, MEMF_CHIP | MEMF_CLEAR);
}

Gtia9CopperList::~Gtia9CopperList()
{
    if (blank_) { FreeMem(blank_, 64); blank_ = 0; }
}

// Write one plane-pointer quad (4 planes) at list index `idx`, stepping `stride` per plane.
static void emitPlanes(uint32_t* d, uint32_t idx, uint32_t base, int stride)
{
    for (int p = 0; p < kBP4; p++, base += (uint32_t)stride) {
        const uint16_t reg = (uint16_t)(bpl1pth + (p << 2));
        d[idx++] = copperMove(reg,     (uint16_t)(base >> 16));
        d[idx++] = copperMove(reg + 2, (uint16_t)(base & 0xFFFF));
    }
}

void Gtia9CopperList::buildLayout(const Bitmap& field, uint16_t topLines, uint16_t rows,
                                  const uint16_t* pal16, const Sprite& nullSprite)
{
    uint32_t* d = data_;
    field_ = &field;

    // Full-screen 4bp interleaved playfield (BPLCON0 + the interleaved modulo).
    setPlayfield(INDEX_PLAYFIELD, kW, kH, kBP4, /*interleaved*/true,
                 /*hires*/false, /*interlace*/false, /*dualPlayfield*/false,
                 /*holdAndModify*/false, kCenterY);

    // Both scenes run at Atari priority 1, where the players sit in front of PF2/PF3 — and in
    // GTIA mode 9 every playfield pixel IS the background register, so all four sprite pairs
    // belong in front.  BPLCON2 = 0 (PF1P = PF2P = 0) says exactly that.  Emitted as a MOVE
    // rather than left to a CPU write because BPLCON2 is write-only hardware that persists
    // across copper lists, so a MOVE-less list silently inherits the previous scene's value
    // (see the amiga-copper-lessons memory).
    d[INDEX_BPLCON2] = copperMove(bplcon2, 0x0000);

    // The scene's 16 luminances.  color00 is also what the blank regions and the border show,
    // and pen 0 == COLBK's luminance 0, so one table covers all of it.
    for (int i = 0; i < 16; i++)
        d[INDEX_PAL + i] = copperMove((uint16_t)(color00 + (i << 1)), pal16[i]);

    // Sprite colour registers: colour 1 of each pair is set per frame (setPairColor); colours
    // 2 and 3 are unused here (no attached / multi-colour sprite pairs) but are emitted black
    // so the list never inherits a foreign scene's value.
    for (int pair = 0; pair < 4; pair++) {
        const uint16_t base = (uint16_t)(color17 + (pair << 3));   // COLOR17/21/25/29
        d[INDEX_SPRCOL + pair * 3 + 0] = copperMove(base,     0x000);
        d[INDEX_SPRCOL + pair * 3 + 1] = copperMove(base + 2, 0x000);
        d[INDEX_SPRCOL + pair * 3 + 2] = copperMove(base + 4, 0x000);
    }

    for (int s = 0; s < 8; s++)
        showSprite(INDEX_SPRITES + s * 2, (uint16_t)s, nullSprite);

    // Region A — the display list's leading `$70` blank scanlines.
    d[INDEX_TOP_MOD + 0] = copperMove(bpl1mod, (uint16_t)(-kLineBytes));
    d[INDEX_TOP_MOD + 1] = copperMove(bpl2mod, (uint16_t)(-kLineBytes));
    emitPlanes(d, INDEX_TOP_BPL, (uint32_t)blank_, 0);

    // Region B — the mode-F rows.  WAIT at the END of the line before the region (x = 0xE0, in
    // the horizontal blank) so the pointers are final before that line's data fetch.
    d[INDEX_WIN_WAIT]    = copperWait(kDisplayTop + topLines - 1, 0xE0);
    d[INDEX_WIN_MOD + 0] = copperMove(bpl1mod, (uint16_t)kModInterleaved);
    d[INDEX_WIN_MOD + 1] = copperMove(bpl2mod, (uint16_t)kModInterleaved);
    setWindowRow(0);

    // Region C — past the end of the display list: COLBK for whatever is left of the window.
    d[INDEX_BOT_WAIT]    = copperWait(kDisplayTop + topLines + rows - 1, 0xE0);
    d[INDEX_BOT_MOD + 0] = copperMove(bpl1mod, (uint16_t)(-kLineBytes));
    d[INDEX_BOT_MOD + 1] = copperMove(bpl2mod, (uint16_t)(-kLineBytes));
    emitPlanes(d, INDEX_BOT_BPL, (uint32_t)blank_, 0);

    d[INDEX_TERMINATOR] = copperWait(255, 254);
}

void Gtia9CopperList::setWindowRow(uint16_t row)
{
    if (!field_) return;
    emitPlanes(data_, INDEX_WIN_BPL,
               (uint32_t)field_->data + (uint32_t)row * (uint32_t)kRowBytes, kLineBytes);
}

void Gtia9CopperList::setPairColor(uint16_t pair, uint16_t c)
{
    data_[INDEX_SPRCOL + pair * 3] = copperMove((uint16_t)(color17 + (pair << 3)), c);
}

void Gtia9CopperList::setSpriteOperand(uint16_t channel, const uint16_t* data)
{
    const uint32_t a = (uint32_t)data;
    const uint16_t reg = (uint16_t)(spr1pth + (channel << 2));
    data_[INDEX_SPRITES + channel * 2 + 0] = copperMove(reg,     (uint16_t)(a >> 16));
    data_[INDEX_SPRITES + channel * 2 + 1] = copperMove(reg + 2, (uint16_t)(a & 0xFFFF));
}
