#!/usr/bin/env python3
"""Convert an indexed-colour PNG to Amiga OCS interleaved 4-bitplane raw.

Output:
  <dst>.raw       — interleaved bitplane data (goes into .MEMF_CHIP via incbin.s)
  <dst>_pal.h     — C++ OCS 12-bit palette array (include in AttractScene.cpp)

Usage:
  python3 tools/png2raw.py <src.png> <dst-base>
    e.g.  python3 tools/png2raw.py ../atari000.png assets/attract

Crop/size flags (edit below or pass as env vars):
  CROP_X  — pixels to remove from each horizontal side (default 8, 336→320)
  CROP_Y  — pixels to remove from the top (default 0)
  WIDTH   — output width in pixels (must be multiple of 16; default 320)
  HEIGHT  — output height in pixels (default 200)

The output format matches the dA JoRMaS Bitmap interleaved layout:
  For each row y: plane0_row | plane1_row | plane2_row | plane3_row
  Each plane row is WIDTH/8 bytes (word-aligned).
"""

import os
import sys
from PIL import Image

def png_to_raw(src_path, dst_base,
               crop_x=8, crop_y=0, width=320, height=200):

    img = Image.open(src_path)
    print(f"Source: {img.size} {img.mode}")

    # Ensure palette mode with <=16 colours
    if img.mode != 'P':
        img = img.convert('P', palette=Image.ADAPTIVE, colors=16)
    # Crop to target size
    img = img.crop((crop_x, crop_y, crop_x + width, crop_y + height))
    print(f"Cropped to: {img.size}")

    pixels = list(img.getdata())
    unique_sorted = sorted(set(pixels))
    n_colors = len(unique_sorted)
    if n_colors > 16:
        # Re-quantise to 16
        img = img.quantize(16)
        pixels = list(img.getdata())
        unique_sorted = sorted(set(pixels))
        n_colors = len(unique_sorted)
        print(f"Re-quantised to {n_colors} colours")
    else:
        print(f"Colours used: {n_colors}")

    # Compact remap: ensure indices are 0..n_colors-1
    remap = {old: new for new, old in enumerate(unique_sorted)}
    pixels_r = [remap[p] for p in pixels]

    # Build OCS palette (12-bit 0xRGB per entry, R/G/B are top 4 bits of 8-bit)
    pal_raw = img.getpalette()
    ocs_pal = []
    for idx in unique_sorted:
        r = pal_raw[idx * 3] >> 4
        g = pal_raw[idx * 3 + 1] >> 4
        b = pal_raw[idx * 3 + 2] >> 4
        ocs_pal.append((r << 8) | (g << 4) | b)
    while len(ocs_pal) < 16:
        ocs_pal.append(0x000)  # unused entries = black

    # Build interleaved bitplane data
    bpr = width >> 3                  # bytes per plane row (40 for 320)
    row_stride = 4 * bpr              # interleaved row = 4 planes × bpr
    data = bytearray(height * row_stride)

    for y in range(height):
        for x in range(width):
            v = pixels_r[y * width + x]
            bx = x >> 3
            bit = 7 - (x & 7)        # MSB = leftmost pixel (Amiga convention)
            for p in range(4):
                if (v >> p) & 1:
                    data[y * row_stride + p * bpr + bx] |= (1 << bit)

    raw_path = dst_base + '.raw'
    with open(raw_path, 'wb') as f:
        f.write(data)
    print(f"Wrote {len(data)} bytes → {raw_path}  ({width}×{height} px, 4 planes interleaved)")

    pal_path = dst_base + '_pal.h'
    with open(pal_path, 'w') as f:
        f.write('// Attract-screen OCS palette — generated by tools/png2raw.py\n')
        f.write('// 16 entries, 12-bit 0x0RGB each (top nibble unused on OCS).\n')
        f.write('static const uint16_t kAttractPalette[16] = {\n')
        for i, c in enumerate(ocs_pal):
            src_rgb = ''
            if i < n_colors:
                idx = unique_sorted[i]
                r8, g8, b8 = pal_raw[idx*3:idx*3+3]
                src_rgb = f'  // #{r8:02x}{g8:02x}{b8:02x}'
            else:
                src_rgb = '  // (unused)'
            f.write(f'    0x{c:03x},{src_rgb}\n')
        f.write('};\n')
    print(f"Wrote palette → {pal_path}")


if __name__ == '__main__':
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    cx = int(os.getenv('CROP_X', '8'))
    cy = int(os.getenv('CROP_Y', '0'))
    w  = int(os.getenv('WIDTH',  '320'))
    h  = int(os.getenv('HEIGHT', '200'))
    png_to_raw(sys.argv[1], sys.argv[2], crop_x=cx, crop_y=cy, width=w, height=h)
