#!/usr/bin/env python3
"""Generate the GTIA mode 9 (16-luminance) Amiga OCS palettes for the boot scenes.

WHY THIS EXISTS — amiga/assets/atari_pal.h cannot serve GTIA mode 9.  That table is
indexed by an Atari colour BYTE and deliberately ignores bit 0, because a GTIA colour
REGISTER stores luminance in bits 3-1 (three bits, eight levels) and bit 0 is unused.
GTIA mode 9 is the one case where the low four bits are all significant: the ANTIC-F
nibble replaces the whole luminance field of COLBK, which is exactly what makes it
"one hue, SIXTEEN luminances".  Running it through atariToOCS() collapses those to
eight and puts visible banding in the station hull and the logo lettering.

So: same YIQ formula as PlatformSDL::buildPalette (the one the whole port's palette
was calibrated against, hue angles and all), evaluated at HALF luminance steps
l = n/2 for n = 0..15 instead of the integer l = 0..7.  n even therefore reproduces
atariToOCS(hue | 2l) exactly, and n odd interpolates on the same curve.

Only two hues are ever needed — $00 (the station, greyscale) and $10 (the logo, gold)
— and the freestanding Amiga build has no libm, so the tables are emitted as
constants.  Run this and paste the output into src/platform/amiga/StationCopperList.cpp
if either hue ever changes:  python3 tools/gen_gtia9_pal.py
"""
import math

# PlatformSDL::buildPalette, verbatim.
HUE_ANGLES = [0, 344.0, 10.5, 37.0, 63.5, 90.0, 116.5, 143.0,
              169.5, 196.0, 222.5, 249.0, 275.5, 302.0, 328.5, 355.0]
CHROMA = 49.0


def ocs(hue, l):
    """Atari hue index + (possibly fractional) 3-bit luminance -> 12-bit OCS 0xRGB."""
    Y = 1.5 * l * l + 20.5 * l + 4.0
    if hue == 0:
        r = g = b = Y
    else:
        a = math.radians(HUE_ANGLES[hue])
        I = CHROMA * math.cos(a)
        Q = CHROMA * math.sin(a)
        r = Y + 0.956 * I + 0.621 * Q
        g = Y - 0.272 * I - 0.647 * Q
        b = Y - 1.106 * I + 1.703 * Q
    # 0..255 -> 0..15, the same rounding amiga/assets/atari_pal.h used.
    def q(v):
        return max(0, min(15, int(round(max(0.0, min(255.0, v)) * 15.0 / 255.0))))
    return (q(r) << 8) | (q(g) << 4) | q(b)


for hue, what in ((0x0, 'station, greyscale'), (0x1, 'logo, gold')):
    vals = [ocs(hue, n / 2.0) for n in range(16)]
    print('// GTIA mode 9, COLBK hue $%X0 (%s) — pen n = luminance n/15.' % (hue, what))
    print('// Generated by tools/gen_gtia9_pal.py; even n == atariToOCS($%X0 | n).' % hue)
    print('static const uint16_t kGtia9Pal%X[16] = {' % hue)
    for i in range(0, 16, 8):
        print('    ' + ' '.join('0x%03X,' % v for v in vals[i:i + 8]))
    print('};')
    print()
