#!/usr/bin/env python3
"""Developer tool: derive the copyright-free ROM-offset boot recipe.

This is intentionally not part of an end-user build.  It compares the audited legacy
sparse boot stream with the known XEGS ROM and emits only triples of destination address,
package offset and length.  No original byte is emitted.  The checked-in result lets both
the BSS/WHDLoad and standalone builds recreate the established v4.1 stage snapshots from
the user-owned v5.0 data package.
"""

from __future__ import annotations

import argparse
import collections
import struct
from pathlib import Path

from extract_rom_data import ROM_RANGES, checked_rom, extract


def package_offset(rom_offset: int) -> int:
    out = 0
    for start, size in ROM_RANGES:
        if start <= rom_offset < start + size:
            return out + rom_offset - start
        out += size
    raise ValueError(hex(rom_offset))


def chunks(blob: bytes):
    pos = 0
    while pos < len(blob):
        if pos + 4 > len(blob):
            raise SystemExit("truncated sparse header")
        addr, size = struct.unpack_from(">HH", blob, pos)
        pos += 4
        data = blob[pos:pos + size]
        if len(data) != size:
            raise SystemExit("truncated sparse payload")
        pos += size
        yield addr, data


def derive(rom: bytes, sparse: bytes):
    allowed = []
    for start, size in ROM_RANGES:
        allowed.extend(range(start, start + size))
    by_first = collections.defaultdict(list)
    for pos in allowed:
        by_first[rom[pos]].append(pos)

    ops = []
    stage_ends = []
    for addr, data in chunks(sparse):
        i = 0
        while i < len(data):
            best_len = 0
            best_pos = -1
            for candidate in by_first[data[i]]:
                n = 1
                while (i + n < len(data) and candidate + n < len(rom)
                       and data[i + n] == rom[candidate + n]):
                    try:
                        package_offset(candidate + n)
                    except ValueError:
                        break
                    n += 1
                if n > best_len:
                    best_len, best_pos = n, candidate
            if best_pos < 0:
                raise AssertionError((addr, i, data[i]))
            ops.append((addr + i, package_offset(best_pos), best_len))
            i += best_len
        if addr <= 0x02E3 and addr + len(data) > 0x02E2:
            stage_ends.append(len(ops))
    if len(stage_ends) != 4:
        raise SystemExit(f"expected four stages, found {len(stage_ends)}")
    return ops, stage_ends


def render(ops, stage_ends) -> str:
    lines = [
        "/* GENERATED by tools/gen_rom_recipe.py; contains offsets/lengths only. */",
        "#ifndef ROF_DATA_RECIPE_H",
        "#define ROF_DATA_RECIPE_H",
        "typedef struct { unsigned short dst, src, len; } RofDataCopy;",
        f"#define ROF_DATA_COPY_COUNT {len(ops)}u",
        "static const RofDataCopy kRofDataCopies[ROF_DATA_COPY_COUNT] = {",
    ]
    lines += [f"    {{0x{d:04X}, 0x{s:04X}, 0x{n:04X}}}," for d, s, n in ops]
    lines += [
        "};",
        "static const unsigned short kRofDataStageEnds[4] = { "
        + ", ".join(f"{n}u" for n in stage_ends) + " };",
        "#endif",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("rom", type=Path)
    parser.add_argument("sparse", type=Path)
    parser.add_argument("--patch-path", default="src/rof_data_recipe.h",
                        help="emit an apply_patch patch adding this path")
    args = parser.parse_args()
    rom = checked_rom(args.rom)
    sparse = args.sparse.read_bytes()
    ops, stage_ends = derive(rom, sparse)
    body = render(ops, stage_ends)
    print("*** Begin Patch")
    print(f"*** Add File: {args.patch_path}")
    for line in body.splitlines():
        print("+" + line)
    print("*** End Patch")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
