#!/usr/bin/env python3
"""Bake the Lucasfilm Games logo bitmap (scene 1) into src/rof_logo_field.h.

WHY BAKED (user decision, docs/logo-station-plan.md §1.3).  The logo lives in XEX segment 5
($5000-$536F), which segment 16 overwrites before the image Ghidra disassembles — so it is
absent from listing.txt and from rof_gen.c, and its $5111 stroke plotter cannot be reached
by the transpiler pipeline.  Porting the plotter by hand would buy NOTHING VISIBLE: the
Atari draws with playfield DMA OFF (DMACTL = $20) and only reveals the finished picture
(DMACTL = $3A), so a baked bitmap is bit-identical to what the player sees.

TWO PHASES, because the reveal is not the end of the drawing: the Atari shows "LUCASFILM"
for 86 frames (the $51EF VBI counting ZP $90 down from $56) and only then draws "GAMES".
Both states are captured, and they differ in exactly one 11x13-byte rectangle, so this
emits the LUCASFILM field whole plus that rectangle as an overlay.

Sources (both real atari800 savestates; RAM base 0x86 in the gunzipped .a8s — note
tools/extract_a8s_ram.py cannot read these, its anchor is not loaded yet at boot):
  a800dumps/lucasfilm.a8s  RTCLOK_LOW $14, ZP $90 = $4A  -> mid-LUCASFILM
  a800dumps/logo.a8s       RTCLOK_LOW $6A, ZP $90 = $00  -> after GAMES
Both are cross-checked here against the $51EF VBI model before anything is emitted.

  python3 tools/gen_logo_field.py > src/rof_logo_field.h

The bake is NOT a magic blob: tools/plot_logo_ref.py re-runs the Atari's own $5111 stroke
plotter over the ~130 bytes at $525F and reproduces what this script emits, byte for byte.
Run it if the header is ever regenerated or doubted.
"""
import gzip
import sys

BASE = 0x86            # RAM offset inside the gunzipped .a8s
FIELD = 0x60A3         # the display list's LMS operand
ROWS, STRIDE = 62, 40


def ram(path):
    return gzip.open(path, 'rb').read()[BASE:BASE + 65536]


a = ram('a800dumps/lucasfilm.a8s')
b = ram('a800dumps/logo.a8s')

# Sanity: both must be the logo scene, with VVBLKI = $51EF and segment 5's code at $5000.
for m, what in ((a, 'lucasfilm.a8s'), (b, 'logo.a8s')):
    assert bytes(m[0x5000:0x5006]) == bytes.fromhex('A2FF869 0E88E'.replace(' ', '')), what
    assert m[0x0222] == 0xEF and m[0x0223] == 0x51, what
    assert bytes(m[0x6000:0x600B]) == bytes.fromhex('7070707070707070 4FA360'.replace(' ', '')), what
# ...and lucasfilm.a8s must be the EARLIER phase: $90 still counting, the four AUDF
# accumulators ramped from their $5254 seeds by exactly ($56 - $90) steps of 1/2/3/0.
elapsed = 0x56 - a[0x90]
for zp, seed, step in ((0x93, 0x2A, 1), (0x95, 0x22, 2), (0x97, 0x00, 3), (0x99, 0x87, 0)):
    assert a[zp] == (seed + elapsed * step) & 0xFF, hex(zp)
assert b[0x90] == 0 and a[0x91] == 0x7F, 'phase order'

A = bytes(a[FIELD:FIELD + ROWS * STRIDE])
B = bytes(b[FIELD:FIELD + ROWS * STRIDE])
diff = [i for i in range(len(A)) if A[i] != B[i]]
r0, r1 = min(i // STRIDE for i in diff), max(i // STRIDE for i in diff)
c0, c1 = min(i % STRIDE for i in diff), max(i % STRIDE for i in diff)

out = sys.stdout
out.write('/* rof_logo_field.h — the baked Lucasfilm Games logo bitmap (scene 1, boot INITAD\n')
out.write(' * $5000).  GENERATED by tools/gen_logo_field.py from two atari800 savestates; see that\n')
out.write(' * script for why the logo is baked rather than plotted, and for the two-phase reveal.\n')
out.write(' *\n')
out.write(' * ANTIC mode F under GTIA mode 9 (PRIOR $41): %d rows of %d bytes at $%04X, each byte\n'
          % (ROWS, STRIDE, FIELD))
out.write(' * two 4-bit LUMINANCES of the COLBK hue $10 (gold).  %d bytes.\n' % len(A))
out.write(' */\n')
out.write('#ifndef ROF_LOGO_FIELD_H\n#define ROF_LOGO_FIELD_H\n\n')
out.write('#define ROF_LOGO_FIELD_ADDR  0x%04Xu\n' % FIELD)
out.write('#define ROF_LOGO_FIELD_ROWS  %d\n' % ROWS)
out.write('#define ROF_LOGO_FIELD_STRIDE %d\n\n' % STRIDE)
out.write('/* Phase 1: "LUCASFILM" alone, which is what the reveal (DMACTL = $3A) uncovers. */\n')
out.write('static const unsigned char kLogoField[%d] = {\n' % len(A))
for r in range(ROWS):
    row = A[r * STRIDE:(r + 1) * STRIDE]
    out.write('    /* row %2d */ %s\n' % (r, ' '.join('0x%02X,' % v for v in row)))
out.write('};\n\n')
out.write('/* Phase 2: "GAMES", drawn 86 frames later ($51EF counts ZP $90 down from $56).  The\n')
out.write(' * two captures differ in exactly this rectangle — rows %d..%d, bytes %d..%d.  */\n'
          % (r0, r1, c0, c1))
out.write('#define ROF_LOGO_GAMES_ROW  %d\n' % r0)
out.write('#define ROF_LOGO_GAMES_COL  %d\n' % c0)
out.write('#define ROF_LOGO_GAMES_ROWS %d\n' % (r1 - r0 + 1))
out.write('#define ROF_LOGO_GAMES_COLS %d\n' % (c1 - c0 + 1))
out.write('static const unsigned char kLogoGames[%d] = {\n' % ((r1 - r0 + 1) * (c1 - c0 + 1)))
for r in range(r0, r1 + 1):
    row = B[r * STRIDE + c0:r * STRIDE + c1 + 1]
    out.write('    /* row %2d */ %s\n' % (r, ' '.join('0x%02X,' % v for v in row)))
out.write('};\n\n#endif /* ROF_LOGO_FIELD_H */\n')
