#!/usr/bin/env python3
"""Single source of truth for the cartridge-package layout; generate C/BASM constants."""

from __future__ import annotations

import argparse
from pathlib import Path


ROM_SIZE = 65536
ROM_SHA256 = "1eb18e2a1ff31f43871a5e4e21e73f61b7659177d33d2cdbb29f36530b9f4d68"
ROM_RANGES = ((0x0000, 0x75D1), (0x8000, 0x113B), (0xE000, 0x1FDA))
PACKAGE_SIZE = sum(size for _, size in ROM_RANGES)
PACKAGE_CRC32 = 0xDA1DDF54


def generated() -> tuple[str, str, str]:
    package_offsets = []
    pos = 0
    for _rom, size in ROM_RANGES:
        package_offsets.append(pos)
        pos += size
    c = ["/* Generated by tools/rof_data_layout.py; do not edit. */",
         "#ifndef ROF_DATA_LAYOUT_H", "#define ROF_DATA_LAYOUT_H"]
    asm = ["; Generated by tools/rof_data_layout.py; do not edit."]
    for i, ((rom, size), package) in enumerate(zip(ROM_RANGES, package_offsets)):
        c += [f"#define ROF_DATA_ROM{i}_OFFSET 0x{rom:04X}ul",
              f"#define ROF_DATA_ROM{i}_SIZE   0x{size:04X}ul",
              f"#define ROF_DATA_PACK{i}_OFFSET 0x{package:04X}ul"]
        asm += [f"data_ROM{i}_OFFSET = ${rom:04x}", f"data_ROM{i}_SIZE = ${size:04x}",
                f"data_PACK{i}_OFFSET = ${package:04x}"]
    c += [f"#define ROF_DATA_PACKAGE_SIZE 0x{PACKAGE_SIZE:04X}ul",
          f"#define ROF_DATA_PACKAGE_CRC32 0x{PACKAGE_CRC32:08X}ul", "#endif", ""]
    asm += [f"data_SIZE = ${PACKAGE_SIZE:08x}", f"data_CRC32 = ${PACKAGE_CRC32:08x}", ""]
    gas = ["| Generated by tools/rof_data_layout.py; do not edit.",
           f".equ ROF_DATA_PACKAGE_SIZE_ASM, 0x{PACKAGE_SIZE:04X}", ""]
    return "\n".join(c), "\n".join(asm), "\n".join(gas)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generated()
    outputs = ((Path("src/rof_data_layout.h"), content[0]),
               (Path("whdload/rof_data_layout.i"), content[1]),
               (Path("src/platform/amiga/rof_data_layout.inc"), content[2]))
    for path, content in outputs:
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"{path}: stale; run tools/rof_data_layout.py")
            print(f"verified {path}")
        else:
            path.write_text(content)
            print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
